feat: Implement teams dashboard widget
nextcloud/circles pull request #1510
Opened 2024-02-20 14:30 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

2024-02-20 17:06 UTC, jancborchardt requested changes
The avatar placeholders only fit for individual people, in this case it's better to just use the teams icon for each team.
Yes it's some duplication, but also helps to have a recognizable icon everywhere.

Also (apart from the vertical alignment you noted), the icons should be horizontally aligned below the heading icon of the widget, just like the text should be left-aligned with the heading text. Currently everything is a bit shifted to the right.

2024-02-20 17:20 UTC, juliushaertl commented
> The avatar placeholders only fit for individual people, in this case it's better to just use the teams icon for each team.

We currently don't have one. Once the stretch goal https://github.com/nextcloud/circles/issues/1508 is there we can do that, but for now this is based on what we have there in the existing circles UI already:

![Screenshot 2024-02-20 at 18 20 01](https://github.com/nextcloud/circles/assets/3404133/7fa58cc9-534f-4b22-9cf0-da9f2b10c38a)

> Also (apart from the vertical alignment you noted), the icons should be horizontally aligned below the heading icon of the widget, just like the text should be left-aligned with the heading text. Currently everything is a bit shifted to the right.

Noted, will check how we can address that generally (as the other widgets show the same issue)

2024-02-20 19:39 UTC, juliushaertl commented
Quick note on the button, currently we only have options to specify a more text and a button when the list is empty (please ignore the missing icon):

empty | more
|---|---|
<img width="350" alt="Screenshot 2024-02-20 at 20 36 55" src="https://github.com/nextcloud/circles/assets/3404133/4bcb7537-f92a-4ea3-8e63-4ba63ead49cd"> | <img width="340" alt="Screenshot 2024-02-20 at 20 36 33" src="https://github.com/nextcloud/circles/assets/3404133/4938a770-b638-4f59-9e0c-1228926b8c04">


@jancborchardt Is that enough? Otherwise we need a generic design spec on how list widgets should handle this as I'd like to keep the implementation without custom frontend implementation to account for the dashboard load performance improvements that this brings and also make sure it works on client integrations.

2024-02-22 10:43 UTC, marcoambrosini commented
@juliushaertl could we use the empty content component with an add icon and an explanation of what a team is?

2024-02-22 10:48 UTC, juliushaertl commented
Yes, though we need to extend the server API for that, would follow up in separate PRs then to keep things moving

2024-03-03 23:41 UTC, ArtificialOwl commented
Do we need to display all circles or only the one current user is member of ?
It _might_ be heavy on resources to use `getCircles()` from the dashboard. This method should only be used from the contact app to display all **available/visible** circles.

`probeCircles()` is lighter and will returns all circles current user is a member of.

Now, if we display circles based on membership, we can also imagine:

- create a newfield in circles table to store a `'last_event'` value in database,
- update `last_event` when a new share to circle is created/updated (or any other event),
- add a way to order by `'last_event'` when calling `probeCircles()` _(DataProbe)_

The result would be that top of the list are showing circles with more recent activity

2024-03-04 12:39 UTC, juliushaertl commented
> Do we need to display all circles or only the one current user is member of ? It _might_ be heavy on resources to use `getCircles()` from the dashboard. This method should only be used from the contact app to display all **available/visible** circles.
>
> `probeCircles()` is lighter and will returns all circles current user is a member of.

Ah thanks, I switched that as we're only interested in the ones where a user is member

> Now, if we display circles based on membership, we can also imagine:
> 
>     * create a newfield in circles table to store a `'last_event'` value in database,
> 
>     * update `last_event` when a new share to circle is created/updated (or any other event),
> 
>     * add a way to order by `'last_event'` when calling `probeCircles()` _(DataProbe)_
> 
> 
> The result would be that top of the list are showing circles with more recent activity

Won't get to that in this iteration, we can track this as a follow up of course as it generally makes sense I think.

2024-03-04 12:41 UTC, juliushaertl commented
@ArtificialOwl Mind to double check the fixup commit for the prope adjustment? I'm also not sure what effect the details have but not requesting any also gives us enough information i think.

2024-03-04 15:22 UTC, ArtificialOwl approved these changes

2024-03-04 21:47 UTC, merged

2024-03-05 13:33 UTC, nickvergessen commented on lib/Dashboard/TeamDashboardWidget.php
> +			$this->urlGenerator->linkToRoute('contacts.page.index')
this breaks when the contacts app is not enabled.
Circles is default enabled, but the contacts app is not even shipped:
https://github.com/nextcloud/server/blob/60681fb8240843b294db02593811a9c600b27335/core/shipped.json#L54

```
Technical details

    Request ID: 1WWtRvraU7IKjR7k0KyE
    Type: ReflectionException
    Code: -1
    Message: Class "OCA\Contacts\Controller\PageController" does not exist
    File: /var/www/html/lib/private/Route/Router.php
    Line: 469


Trace

#0 /var/www/html/lib/private/Route/Router.php(469): ReflectionClass->__construct()
#1 /var/www/html/lib/private/Route/Router.php(161): OC\Route\Router->getAttributeRoutes()
#2 /var/www/html/lib/private/Route/Router.php(400): OC\Route\Router->loadRoutes()
#3 /var/www/html/lib/private/Route/CachingRouter.php(65): OC\Route\Router->generate()
#4 /var/www/html/lib/private/URLGenerator.php(103): OC\Route\CachingRouter->generate()
#5 /var/www/html/apps/circles/lib/Dashboard/TeamDashboardWidget.php(153): OC\URLGenerator->linkToRoute()
#6 /var/www/html/apps/circles/lib/Dashboard/TeamDashboardWidget.php(123): OCA\Circles\Dashboard\TeamDashboardWidget->getTeamPage()
#7 /var/www/html/apps/dashboard/lib/Controller/DashboardController.php(78): OCA\Circles\Dashboard\TeamDashboardWidget->getUrl()
#8 [internal function]: OCA\Dashboard\Controller\DashboardController->OCA\Dashboard\Controller\{closure}()
#9 /var/www/html/apps/dashboard/lib/Controller/DashboardController.php(73): array_map()
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\Dashboard\Controller\DashboardController->index()
#11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController()
#12 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch()
#13 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main()
#14 /var/www/html/lib/base.php(1065): OC\Route\Router->match()
#15 /var/www/html/index.php(49): OC::handleRequest()
#16 {main}
```

Maybe add that app enabled check to the `isEnabled` of the widget?